In [1]:
a = 101

In [2]:
# id 返回内存地址
id(a)

10598312

In [3]:
a += 1

In [4]:
# 修改a之后内存地址变化
id(a)

10598288

In [5]:
b = a

In [6]:
# 我们发现b与a的id完全一样
# 所以 b = a 这个操作讲b与a指向同一个内存
id(b)

10598288

In [7]:
b += 1

In [8]:
# 再次对b进行操作之后,b被重新分配位置
# 此时a与b指向位置已经不同
id(b)

10598264

In [9]:
# 看a, b是否指向同一个对象
a is b

False

In [10]:
b = a

In [11]:
a is b

True

In [12]:
a = 5
b = 5
a is b

In [21]:
# python 只有对很小的或者常用的数进行内存复用
# 对较大的数或浮点数不会复用
a = 505
b = 505
a is b

In [15]:
# python 只有对很小的或者常用的数进行内存复用
# 对较大的数或浮点数不会复用
a = 505.5
b = 505.5
a is b

### 可变类型

In [32]:
a = [101, 102, 103]

In [33]:
b = a

In [34]:
id(a)

140145386986384

In [35]:
b[1] = 300

In [36]:
id(a)

140145386986384

In [37]:
id(a[0])

10598312

In [38]:
id(a[1])

15756832

In [39]:
id(a[2])

10598264

### numpy

In [40]:
import numpy as np

In [41]:
a = np.array([5, 1, 2, 3])

In [42]:
a.itemsize

8

In [43]:
a.dtype

dtype('int64')

In [44]:
# numpy类型初始化结束之后，不能强制改变类型
a[0] = 5.8

In [45]:
a

array([5, 1, 2, 3])

In [46]:
# 因为ndarray存储在连续内存，所以换了一种方式读后
# 会有如下效果
a.view('int32')

array([5, 0, 1, 0, 2, 0, 3, 0], dtype=int32)

### numpy 生成方式

In [47]:
c = np.array(a)

In [48]:
# 如上方法使用了复制
# 所以 c 与 a 不是一个东西
c is a

False

In [49]:
c = np.asarray(a)

In [50]:
# 此时，如果a是array，则不做任何操作
c is a

True

In [51]:
c = np.asarray(a, dtype='float32')

In [52]:
# 改变a类型后不再是一个东西
c is a

False

### 形状操作

In [53]:
a = np.arange(36)

In [54]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [55]:
a.shape

(36,)

In [56]:
a.shape = 6, 6

In [57]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [59]:
# 该方法返回了一个新的4 x 9，但不对原来a做任何操作
# 实际上是一个copy操作
a.reshape(4, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [60]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [61]:
# 参数'-1'表示并不知道第一维是多少，
# 让numpy自己去算
a.reshape(-1, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [62]:
# 此方法直接改变a本身
a.resize(4, 9)

In [63]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [64]:
# 'refcheck'是保护机制
# 有别人引用时不能改变
a.resize(4, 2, refcheck=False)

In [65]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [66]:
# 原来的东西在被砍掉之后直接垃圾回收了
# 所以不够的地方直接补零
a.resize(4, 5, refcheck=False)

In [67]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### array的索引

In [68]:
a[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 0, 0]])

In [69]:
# 凡是带冒号的普通索引都是引用，修改之后会修改a本身
b = a[:2]

In [70]:
b[0, 0] = 100

In [71]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0]])

### 花式索引

In [72]:
a[[0, 3]]

array([[100,   1,   2,   3,   4],
       [  0,   0,   0,   0,   0]])

In [73]:
# 花式索引为复制，不会改变原来的a
b = a[[0, 3]]

In [76]:
b[0, 0] = 50

In [78]:
b

array([[50,  1,  2,  3,  4],
       [ 0,  0,  0,  0,  0]])

In [77]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   0,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0]])

### 广播机制

In [84]:
a = np.arange(100)

In [85]:
a.shape = 10, 10

In [88]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
a[(1, 2, 3, 4), (1, 2, 3, 4)]

array([11, 22, 33, 44])

In [90]:
a[(2, 3), (1, 2, 3, 4)]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (4,) 

In [91]:
a[2, (1, 2, 3, 4)]

array([21, 22, 23, 24])

In [92]:
# broadcasting机制
a[2, ((1, 2), (3, 4))]

array([[21, 22],
       [23, 24]])

In [93]:
# broadcasting机制
a[(2, 2), ((1, 2), (3, 4))]

array([[21, 22],
       [23, 24]])

### 三维花式索引

In [97]:
a.shape = 2, 5, 10

In [98]:
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [101]:
# 两个花式索引
# 先broadcast成: (1, 1, 1), :, (4, 3, 2)
b = a[1, :, (4, 3, 2)]

In [102]:
b.shape

(3, 5)

In [103]:
b

array([[54, 64, 74, 84, 94],
       [53, 63, 73, 83, 93],
       [52, 62, 72, 82, 92]])

### 函数

In [104]:
#　函数也是对象，因为python中一切皆对象
a = 0

In [105]:
a.imag

0

In [106]:
a.real

0

In [107]:
a.conjugate()

0

In [114]:
a = 1.4

In [115]:
id(a)

20141600

In [117]:
# python函数始终传引用
def f(x):
    print id(x)
    x = 1.8
    print id(x)

In [118]:
f(a)

20141600
20141552


In [119]:
a

1.4

In [120]:
id(a)

20141600

#### 另一个例子

In [121]:
def f(x):
    x[1] = 10

In [122]:
a = [1, 2, 3]

In [123]:
# 此时相当于做了 x = a　的操作
f(a)

In [124]:
a

[1, 10, 3]

#### 将函数作为函数的输入

In [125]:
map

<function map>

In [126]:
def f(x):
    return x + 1

In [128]:
# map　是一个高阶函数
map(f, [1, 2, 3, 4, 5])

[2, 3, 4, 5, 6]

In [129]:
# 本质上相当于做了下面操作
[f(x) for x in [1, 2, 3, 4, 5]]

[2, 3, 4, 5, 6]

In [130]:
# 匿名函数，关键字lambda
f = lambda x: x + 1

In [131]:
map(lambda x: x + 6, [1, 2, 3, 4, 5])

[7, 8, 9, 10, 11]

In [132]:
map(lambda x: x * x, [1, 2, 3, 4, 5])

[1, 4, 9, 16, 25]

In [133]:
a = range(10)

In [134]:
map(lambda x: a[x], [1, 2, 3, 4, 5])

[1, 2, 3, 4, 5]

#### global 变量

In [135]:
def f(x):
    x = 12

In [136]:
x = 10

In [137]:
f(x)

In [138]:
x

10

In [139]:
# global关键字修改上一层的参数
def f():
    global x
    x = 12

In [140]:
f()

In [141]:
x

12

### 作用域

In [142]:
import __builtin__

In [143]:
dir(__builtin__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BufferError',
 'BytesWarning',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'NameError',
 'None',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'ReferenceError',
 'RuntimeError',
 'RuntimeWarning',
 'StandardError',
 'StopIteration',
 'SyntaxError',
 'SyntaxWarning',
 'SystemError',
 'SystemExit',
 'TabError',
 'True',
 'TypeError',
 'UnboundLocalError',
 'UnicodeDecodeError',
 'UnicodeEncodeError',
 'UnicodeError',
 'UnicodeTranslateError',
 'UnicodeWarning',
 'UserWarning',
 'ValueError',
 'Warning',
 'ZeroDivisionError',
 '__IPYTHON__',
 '__IPYTHON__active',
 '__debug__',
 '__doc__',
 '__import__